import './Footer.css';

export default function Footer() {
  return (
    <footer className="footer">
      <div className="footer-content">
        <p className="footer-text">
          Edge Daily uses AI to curate and explain trending topics in tech. 
          Content is generated by Claude (Anthropic) with web search for educational purposes. 
          Please verify information through the provided sources.
        </p>
        <p className="footer-links">
          <a href="https://www.anthropic.com" target="_blank" rel="noopener noreferrer">
            Powered by Anthropic
          </a>
        </p>
      </div>
    </footer>
  );
}